version: '3.3'
services:
  redis:
    image: redis
    ports: 
    - "6380:6380"
    volumes:
    - my-vol:/data
  web:
    depends_on:
    - redis
    image: rovandessel/devopsproject
    ports:
    - "6500:3001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
volumes:
  my-vol:
